[build-system]
requires = ["flit_core>=3.9,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "dc_schema"
version = "1.2.0"
description = "Generate JSON schema from python dataclasses"
authors = [
    { name = "Peter Byfield", email = "byfield554@gmail.com" },
    { name = "Frederik Schumacher" },
]
maintainers = [
    { name = "Frederik Schumacher" },
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.12,<3.13"

[project.optional-dependencies]
test = ["pytest>=8", "jsonschema>=4"]
dev = ["black>=24", "nn-semver @ git+https://github.com/fre-sch/nn-semver@master"]

[project.scripts]
dc_schema = "dc_schema.cli:main"

[project.urls]
Repository = "https://github.com/fre-sch/dc_schema"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.black]
line-length = 80
